### ISSUE TITLE
Outdated description for Tree

### ISSUE THREAD

**Issue by eserte** [ronsavage/Tree-Simple#6]
The description for Tree looks outdated --- https://metacpan.org/release/RSAVAGE/Tree-Simple-1.34/view/lib/Tree/Simple.pm#Tree7
* the module is not old anymore (version 1.15 was released this year)
* the base class implements an n-ary tree, not a binary or balanced tree

**Comment by ronsavage** [comment]
Thanx.
I've updated the POD on github, but I don't think this patch is worth releasing as a new version.
